# Deployment do Banco de Dados
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:13.16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: Pg1234
            - name: POSTGRES_USER
              value: ecommerce
            - name: POSTGRES_DB
              value: ecommerce
---
# Deployment da Aplicação
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeshop
spec:
  replicas: 10
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      labels:
        app: fakeshop
    spec:
      containers:
        - name: fakeshop
          image: americojar2014/fake-shop:v1
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: postgre
            - name: DB_USER
              value: ecommerce
            - name: DB_PASSWORD
              value: Pg1234
            - name: DB_NAME
              value: ecommerce
            - name: FLASK_APP
              value: index.py
---
# Service do Banco de Dados
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgre
---
# Service da Aplicação
apiVersion: v1
kind: Service
metadata:
  name: fakeshop
spec:
  type: LoadBalancer #NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000  
  selector:
    app: fakeshop
