name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o codigo
        uses: actions/checkout@v4.2.2

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construcao e envio da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            americojar2014/fake-shop:v${{ github.run_number }}
            americojar2014/fake-shop:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Obtendo o codigo
        uses: actions/checkout@v4.2.2

      - name: Configurando o kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_KUBECONFIG}}

      - name: Aplicando os manifestos no kubernetes
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./k8s/deployment.yaml
          images: |
            americojar2014/fake-shop:v${{ github.run_number }}
